services:
  pg:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_DB: templ_fa
      POSTGRES_USER: marat
      POSTGRES_PASSWORD: 1
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - "8085:8080"
    depends_on:
      - pg

  pgadmin:
    image: dpage/pgadmin4:8.2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5055:80"
    depends_on:
      - pg

volumes:
  pg_data:

