services:

  pg:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_DB: temft
      POSTGRES_USER: marat
      POSTGRES_PASSWORD: 1
    ports:
      - "5434:5432"

  adminer:
    image: adminer
    ports:
      - "8085:8080"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5055:80"
